/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DireitoCriminalRouteImport } from './routes/direito-criminal'
import { Route as PatriciaSavelaRouteImport } from './routes/patricia-savela'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SustentacaoOralRouteImport } from './routes/sustentacao-oral'
import { Route as TribunalDoJuriRouteImport } from './routes/tribunal-do-juri'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoCriminalRoute = DireitoCriminalRouteImport.update({
  id: '/direito-criminal',
  path: '/direito-criminal',
  getParentRoute: () => rootRouteImport,
} as any)
const PatriciaSavelaRoute = PatriciaSavelaRouteImport.update({
  id: '/patricia-savela',
  path: '/patricia-savela',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SustentacaoOralRoute = SustentacaoOralRouteImport.update({
  id: '/sustentacao-oral',
  path: '/sustentacao-oral',
  getParentRoute: () => rootRouteImport,
} as any)
const TribunalDoJuriRoute = TribunalDoJuriRouteImport.update({
  id: '/tribunal-do-juri',
  path: '/tribunal-do-juri',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/contato': typeof ContatoRoute
  '/direito-criminal': typeof DireitoCriminalRoute
  '/patricia-savela': typeof PatriciaSavelaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sustentacao-oral': typeof SustentacaoOralRoute
  '/tribunal-do-juri': typeof TribunalDoJuriRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/contato': typeof ContatoRoute
  '/direito-criminal': typeof DireitoCriminalRoute
  '/patricia-savela': typeof PatriciaSavelaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sustentacao-oral': typeof SustentacaoOralRoute
  '/tribunal-do-juri': typeof TribunalDoJuriRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/contato': typeof ContatoRoute
  '/direito-criminal': typeof DireitoCriminalRoute
  '/patricia-savela': typeof PatriciaSavelaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sustentacao-oral': typeof SustentacaoOralRoute
  '/tribunal-do-juri': typeof TribunalDoJuriRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimento'
    | '/contato'
    | '/direito-criminal'
    | '/patricia-savela'
    | '/politica-de-privacidade'
    | '/sustentacao-oral'
    | '/tribunal-do-juri'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendimento'
    | '/contato'
    | '/direito-criminal'
    | '/patricia-savela'
    | '/politica-de-privacidade'
    | '/sustentacao-oral'
    | '/tribunal-do-juri'
  id:
    | '__root__'
    | '/'
    | '/atendimento'
    | '/contato'
    | '/direito-criminal'
    | '/patricia-savela'
    | '/politica-de-privacidade'
    | '/sustentacao-oral'
    | '/tribunal-do-juri'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentoRoute: typeof AtendimentoRoute
  ContatoRoute: typeof ContatoRoute
  DireitoCriminalRoute: typeof DireitoCriminalRoute
  PatriciaSavelaRoute: typeof PatriciaSavelaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SustentacaoOralRoute: typeof SustentacaoOralRoute
  TribunalDoJuriRoute: typeof TribunalDoJuriRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-criminal': {
      id: '/direito-criminal'
      path: '/direito-criminal'
      fullPath: '/direito-criminal'
      preLoaderRoute: typeof DireitoCriminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patricia-savela': {
      id: '/patricia-savela'
      path: '/patricia-savela'
      fullPath: '/patricia-savela'
      preLoaderRoute: typeof PatriciaSavelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustentacao-oral': {
      id: '/sustentacao-oral'
      path: '/sustentacao-oral'
      fullPath: '/sustentacao-oral'
      preLoaderRoute: typeof SustentacaoOralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribunal-do-juri': {
      id: '/tribunal-do-juri'
      path: '/tribunal-do-juri'
      fullPath: '/tribunal-do-juri'
      preLoaderRoute: typeof TribunalDoJuriRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentoRoute: AtendimentoRoute,
  ContatoRoute: ContatoRoute,
  DireitoCriminalRoute: DireitoCriminalRoute,
  PatriciaSavelaRoute: PatriciaSavelaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SustentacaoOralRoute: SustentacaoOralRoute,
  TribunalDoJuriRoute: TribunalDoJuriRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
