/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtendimentoRouteImport } from './routes/atendimento'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as DireitoCriminalRouteImport } from './routes/direito-criminal'
import { Route as PatriciaSavelaRouteImport } from './routes/patricia-savela'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SustentacaoOralRouteImport } from './routes/sustentacao-oral'
import { Route as TribunalDoJuriRouteImport } from './routes/tribunal-do-juri'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminConteudosIndexRouteImport } from './routes/admin.conteudos.index'
import { Route as AdminConteudosNovoRouteImport } from './routes/admin.conteudos.novo'
import { Route as AdminConteudosIdRouteImport } from './routes/admin.conteudos.$id'
import { Route as ConteudosIndexRouteImport } from './routes/conteudos.index'
import { Route as ConteudosSlugRouteImport } from './routes/conteudos.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoRoute = AtendimentoRouteImport.update({
  id: '/atendimento',
  path: '/atendimento',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoCriminalRoute = DireitoCriminalRouteImport.update({
  id: '/direito-criminal',
  path: '/direito-criminal',
  getParentRoute: () => rootRouteImport,
} as any)
const PatriciaSavelaRoute = PatriciaSavelaRouteImport.update({
  id: '/patricia-savela',
  path: '/patricia-savela',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SustentacaoOralRoute = SustentacaoOralRouteImport.update({
  id: '/sustentacao-oral',
  path: '/sustentacao-oral',
  getParentRoute: () => rootRouteImport,
} as any)
const TribunalDoJuriRoute = TribunalDoJuriRouteImport.update({
  id: '/tribunal-do-juri',
  path: '/tribunal-do-juri',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudosIndexRoute = AdminConteudosIndexRouteImport.update({
  id: '/admin/conteudos/',
  path: '/admin/conteudos/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudosNovoRoute = AdminConteudosNovoRouteImport.update({
  id: '/admin/conteudos/novo',
  path: '/admin/conteudos/novo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConteudosIdRoute = AdminConteudosIdRouteImport.update({
  id: '/admin/conteudos/$id',
  path: '/admin/conteudos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosIndexRoute = ConteudosIndexRouteImport.update({
  id: '/conteudos/',
  path: '/conteudos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosSlugRoute = ConteudosSlugRouteImport.update({
  id: '/conteudos/$slug',
  path: '/conteudos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/contato': typeof ContatoRoute
  '/direito-criminal': typeof DireitoCriminalRoute
  '/patricia-savela': typeof PatriciaSavelaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustentacao-oral': typeof SustentacaoOralRoute
  '/tribunal-do-juri': typeof TribunalDoJuriRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/conteudos/': typeof AdminConteudosIndexRoute
  '/admin/conteudos/novo': typeof AdminConteudosNovoRoute
  '/admin/conteudos/$id': typeof AdminConteudosIdRoute
  '/conteudos/$slug': typeof ConteudosSlugRoute
  '/conteudos/': typeof ConteudosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/contato': typeof ContatoRoute
  '/direito-criminal': typeof DireitoCriminalRoute
  '/patricia-savela': typeof PatriciaSavelaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustentacao-oral': typeof SustentacaoOralRoute
  '/tribunal-do-juri': typeof TribunalDoJuriRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/conteudos': typeof AdminConteudosIndexRoute
  '/admin/conteudos/novo': typeof AdminConteudosNovoRoute
  '/admin/conteudos/$id': typeof AdminConteudosIdRoute
  '/conteudos/$slug': typeof ConteudosSlugRoute
  '/conteudos': typeof ConteudosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atendimento': typeof AtendimentoRoute
  '/contato': typeof ContatoRoute
  '/direito-criminal': typeof DireitoCriminalRoute
  '/patricia-savela': typeof PatriciaSavelaRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sustentacao-oral': typeof SustentacaoOralRoute
  '/tribunal-do-juri': typeof TribunalDoJuriRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/conteudos/': typeof AdminConteudosIndexRoute
  '/admin/conteudos/novo': typeof AdminConteudosNovoRoute
  '/admin/conteudos/$id': typeof AdminConteudosIdRoute
  '/conteudos/$slug': typeof ConteudosSlugRoute
  '/conteudos/': typeof ConteudosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atendimento'
    | '/contato'
    | '/direito-criminal'
    | '/patricia-savela'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sustentacao-oral'
    | '/tribunal-do-juri'
    | '/admin/'
    | '/admin/login'
    | '/admin/conteudos/'
    | '/admin/conteudos/novo'
    | '/admin/conteudos/$id'
    | '/conteudos/$slug'
    | '/conteudos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atendimento'
    | '/contato'
    | '/direito-criminal'
    | '/patricia-savela'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sustentacao-oral'
    | '/tribunal-do-juri'
    | '/admin'
    | '/admin/login'
    | '/admin/conteudos'
    | '/admin/conteudos/novo'
    | '/admin/conteudos/$id'
    | '/conteudos/$slug'
    | '/conteudos'
  id:
    | '__root__'
    | '/'
    | '/atendimento'
    | '/contato'
    | '/direito-criminal'
    | '/patricia-savela'
    | '/politica-de-privacidade'
    | '/sitemap.xml'
    | '/sustentacao-oral'
    | '/tribunal-do-juri'
    | '/admin/'
    | '/admin/login'
    | '/admin/conteudos/'
    | '/admin/conteudos/novo'
    | '/admin/conteudos/$id'
    | '/conteudos/$slug'
    | '/conteudos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtendimentoRoute: typeof AtendimentoRoute
  ContatoRoute: typeof ContatoRoute
  DireitoCriminalRoute: typeof DireitoCriminalRoute
  PatriciaSavelaRoute: typeof PatriciaSavelaRoute
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SustentacaoOralRoute: typeof SustentacaoOralRoute
  TribunalDoJuriRoute: typeof TribunalDoJuriRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminConteudosIndexRoute: typeof AdminConteudosIndexRoute
  AdminConteudosNovoRoute: typeof AdminConteudosNovoRoute
  AdminConteudosIdRoute: typeof AdminConteudosIdRoute
  ConteudosSlugRoute: typeof ConteudosSlugRoute
  ConteudosIndexRoute: typeof ConteudosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento': {
      id: '/atendimento'
      path: '/atendimento'
      fullPath: '/atendimento'
      preLoaderRoute: typeof AtendimentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-criminal': {
      id: '/direito-criminal'
      path: '/direito-criminal'
      fullPath: '/direito-criminal'
      preLoaderRoute: typeof DireitoCriminalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patricia-savela': {
      id: '/patricia-savela'
      path: '/patricia-savela'
      fullPath: '/patricia-savela'
      preLoaderRoute: typeof PatriciaSavelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustentacao-oral': {
      id: '/sustentacao-oral'
      path: '/sustentacao-oral'
      fullPath: '/sustentacao-oral'
      preLoaderRoute: typeof SustentacaoOralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tribunal-do-juri': {
      id: '/tribunal-do-juri'
      path: '/tribunal-do-juri'
      fullPath: '/tribunal-do-juri'
      preLoaderRoute: typeof TribunalDoJuriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudos/': {
      id: '/admin/conteudos/'
      path: '/admin/conteudos'
      fullPath: '/admin/conteudos/'
      preLoaderRoute: typeof AdminConteudosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudos/novo': {
      id: '/admin/conteudos/novo'
      path: '/admin/conteudos/novo'
      fullPath: '/admin/conteudos/novo'
      preLoaderRoute: typeof AdminConteudosNovoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/conteudos/$id': {
      id: '/admin/conteudos/$id'
      path: '/admin/conteudos/$id'
      fullPath: '/admin/conteudos/$id'
      preLoaderRoute: typeof AdminConteudosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/': {
      id: '/conteudos/'
      path: '/conteudos'
      fullPath: '/conteudos/'
      preLoaderRoute: typeof ConteudosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/$slug': {
      id: '/conteudos/$slug'
      path: '/conteudos/$slug'
      fullPath: '/conteudos/$slug'
      preLoaderRoute: typeof ConteudosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtendimentoRoute: AtendimentoRoute,
  ContatoRoute: ContatoRoute,
  DireitoCriminalRoute: DireitoCriminalRoute,
  PatriciaSavelaRoute: PatriciaSavelaRoute,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SustentacaoOralRoute: SustentacaoOralRoute,
  TribunalDoJuriRoute: TribunalDoJuriRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminConteudosIndexRoute: AdminConteudosIndexRoute,
  AdminConteudosNovoRoute: AdminConteudosNovoRoute,
  AdminConteudosIdRoute: AdminConteudosIdRoute,
  ConteudosSlugRoute: ConteudosSlugRoute,
  ConteudosIndexRoute: ConteudosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
